# static resources
signup_html ../static/view/signup.html
signin_html ../static/view/signin.html
home_html ../static/view/home.html
index_html ../static/view/index.html
upload_success_html ../static/view/upload_success.html
auth_js ../static/js/auth.js
avatar_jpeg ../static/img/avatar.jpeg
# log
log_path ../log/CloudDisk.log
# MySQL URL
mysql_url mysql://user:passwd@localhost
# Redis URL
redis_url redis://localhost:6379
# Consul URL
consul_url http://userip:8500/ui/dc1/services
